name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/gtfpl.baradusov.ru/app/
            git pull origin master
            npm ci
            sudo -u nodejs pm2 restart /var/pm2-config/ecosystem.config.js --env production --only gtfpl
